In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)

In [5]:
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.7186e-04, 2.6586e+23, 4.3919e-05],
        [8.1269e+20, 2.7061e+23, 1.7585e-04],
        [2.6582e-06, 1.7663e-04, 6.6819e+22]])


In [7]:
# Random number
x = torch.randn(5,3)
print(x)

tensor([[ 0.2549, -0.5212,  0.4023],
        [ 1.5668, -0.3594, -0.0199],
        [ 0.4858, -1.3606, -0.5628],
        [ 0.1469,  1.5934,  0.7263],
        [-1.4879, -0.0934, -1.8633]])


In [10]:
# Zeros
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [18]:
torch.cuda.is_available()

False